spring:
  application:
    name: chatbotProject

#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url:
#    username:
#    password:

  datasource:
    driver-class-name: org.h2.Driver
    url: 'jdbc:h2:mem:test'   # H2 DB ?? ?? (In-Memory Mode)
    #url: 'jdbc:h2:~/test'    # H2 DB ?? ?? (Embedded Mode)
    username: username        # H2 DB ?? ID (??? ??)
    password:         # H2 DB ?? PW (??? ??)


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  h2:
    console: # H2 DB? ??? ??? ? ?? ??
      enabled: true           # H2 Console ?? ??
      path: /h2-console
